services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: always

  app:
    # Use pre-built image from Docker Hub instead of building locally
    image: keatonhoskins/openhealth:latest
    depends_on:
      - database
      - docling-serve
    volumes:
      - app_data:/app/public/uploads
    ports:
      - "3000:3000"
    restart: always
    # Explicitly disable health check
    healthcheck:
      test: ["CMD", "echo", "ok"]
      interval: 3600s
      retries: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      
      # Security (REQUIRED!)
      AUTH_SECRET: ${AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # Application (IMPORTANT: Set NEXT_PUBLIC_URL to your server's IP!)
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NEXT_PUBLIC_DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NODE_ENV: production
<<<<<<< HEAD
      AUTH_TRUST_HOST: ${NEXT_PUBLIC_URL}
      NEXTAUTH_URL: ${NEXT_PUBLIC_URL}
=======
>>>>>>> feat/build-optimizations

volumes:
  postgres_data:
  app_data:
