version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Document Parser Service
  docling:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: unless-stopped

  # Main Application - Pulls from Docker Hub
  # Replace 'yourdockerhubusername' with your actual Docker Hub username
  app:
    image: keatonhoskins/openhealth:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - database
      - docling
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      
      # Security (MUST CHANGE THESE!)
      AUTH_SECRET: ${AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # Application
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-http://localhost:3000}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NODE_ENV: production
    volumes:
      - app_uploads:/app/public/uploads

volumes:
  postgres_data:
  app_uploads: