services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: always

  app:
    # Use pre-built image from Docker Hub instead of building locally
    image: keatonhoskins/openhealth:latest
    depends_on:
      - database
      - docling-serve
    volumes:
      - app_data:/app/public/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Temporarily disable health check to debug
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    environment:
      # Database
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      
      # Security (REQUIRED!)
      AUTH_SECRET: ${AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # Application
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-http://localhost:3000}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NEXT_PUBLIC_DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NODE_ENV: production
      AUTH_TRUST_HOST: ${NEXT_PUBLIC_URL:-http://localhost:3000}

volumes:
  postgres_data:
  app_data:
