version: '3.8'

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openhealth-network

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: unless-stopped
    networks:
      - openhealth-network

  app:
    # Using the base Node image and running commands directly
    # since we can't build from Dockerfile in Web Editor
    image: node:lts-alpine
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache graphicsmagick curl git &&
      git clone https://github.com/kryptobaseddev/open-health.git . &&
      npm install &&
      npx prisma generate &&
      npm run build &&
      npx prisma db push --accept-data-loss &&
      npm start
      "
    depends_on:
      - database
      - docling-serve
    volumes:
      - app_data:/app/public/uploads
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    ports:
      - "3000:3000"
    networks:
      - openhealth-network
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NODE_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}
      NEXT_PUBLIC_DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}

networks:
  openhealth-network:
    driver: bridge

volumes:
  postgres_data:
  app_data:
  node_modules:
  next_cache: