version: '3.8'

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - openhealth-network

  docling-serve:
    image: ghcr.io/ds4sd/docling-serve:latest
    restart: unless-stopped
    networks:
      - openhealth-network

  app:
    image: ghcr.io/kryptobaseddev/openhealth:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - database
      - docling-serve
    volumes:
      - app_data:/app/public/uploads
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - openhealth-network
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      NODE_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      DEPLOYMENT_ENV: ${DEPLOYMENT_ENV:-local}

networks:
  openhealth-network:
    driver: bridge

volumes:
  postgres_data:
  app_data: